import sanitizeHtml from 'sanitize-html'

/**
 * Sanitizes HTML generated by the Tiptap editor.
 *
 * Raw HTML entered through the administrator-only HTML editor
 * must not be passed through this function.
 */
export function sanitizeEditorHtml(
  value: string | null | undefined,
): string {
  if (!value) return ''

  return sanitizeHtml(value, {
    allowedTags: [
      // Text
      'p',
      'br',
      'strong',
      'b',
      'em',
      'i',
      'u',
      's',
      'strike',
      'mark',
      'sub',
      'sup',

      // Headings
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',

      // Lists
      'ul',
      'ol',
      'li',

      // Blocks
      'blockquote',
      'pre',
      'code',
      'hr',

      // Links and media
      'a',
      'img',

      // Layout used by editor content
      'div',
      'span',

      // Tables
      'table',
      'thead',
      'tbody',
      'tfoot',
      'tr',
      'th',
      'td',
    ],

    allowedAttributes: {
      a: [
        'href',
        'target',
        'rel',
        'title',
      ],

      img: [
        'src',
        'alt',
        'title',
        'width',
        'height',
        'loading',
      ],

      p: [
        'style',
        'data-text-align',
      ],

      h1: [
        'style',
        'data-text-align',
      ],

      h2: [
        'style',
        'data-text-align',
      ],

      h3: [
        'style',
        'data-text-align',
      ],

      h4: [
        'style',
        'data-text-align',
      ],

      h5: [
        'style',
        'data-text-align',
      ],

      h6: [
        'style',
        'data-text-align',
      ],

      span: [
        'style',
        'data-type',
        'data-id',
        'data-label',
      ],

      div: [
        'style',
        'data-type',
      ],

      ul: [
        'data-type',
      ],

      li: [
        'data-type',
        'data-checked',
      ],

      code: [
        'class',
      ],

      table: [
        'style',
      ],

      th: [
        'colspan',
        'rowspan',
        'style',
      ],

      td: [
        'colspan',
        'rowspan',
        'style',
      ],
    },

    allowedClasses: {
      code: [
        /^language-[a-z0-9_-]+$/i,
      ],
    },

    allowedStyles: {
      '*': {
        'text-align': [
          /^left$/,
          /^right$/,
          /^center$/,
          /^justify$/,
        ],
      },

      span: {
        color: [
          /^#[0-9a-f]{3,8}$/i,
          /^rgb\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*\)$/i,
          /^rgba\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*(0|1|0?\.\d+)\s*\)$/i,
        ],

        'background-color': [
          /^#[0-9a-f]{3,8}$/i,
          /^rgb\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*\)$/i,
          /^rgba\(\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*\d{1,3}\s*,\s*(0|1|0?\.\d+)\s*\)$/i,
        ],
      },

      table: {
        width: [
          /^\d+%$/,
          /^\d+px$/,
        ],
      },

      th: {
        'text-align': [
          /^left$/,
          /^right$/,
          /^center$/,
          /^justify$/,
        ],
      },

      td: {
        'text-align': [
          /^left$/,
          /^right$/,
          /^center$/,
          /^justify$/,
        ],
      },
    },

    allowedSchemes: [
      'http',
      'https',
      'mailto',
      'tel',
    ],

    allowedSchemesByTag: {
      img: [
        'http',
        'https',
      ],
    },

    allowProtocolRelative: false,

    transformTags: {
      a: (_tagName, attributes) => {
        const isExternalTarget =
          attributes.target === '_blank'

        return {
          tagName: 'a',
          attribs: {
            ...attributes,
            ...(isExternalTarget
              ? {
                  target: '_blank',
                  rel: 'noopener noreferrer nofollow',
                }
              : {
                  rel: 'nofollow',
                }),
          },
        }
      },

      img: (_tagName, attributes) => ({
        tagName: 'img',
        attribs: {
          ...attributes,
          loading: 'lazy',
        },
      }),
    },
  })
}