import type { Page } from '@/payload-types'
import type { Advertisement } from '@/payload-types'
import type { SeedBoards } from './boards'
import type { SeedContext } from './utils'
import type { SeedMedia } from './media'
import { logStep, upsertByUnique } from './utils'

function boardRefs(...boards: { id: number | string }[]) {
  return boards.map((board) => ({ board: board.id }))
}

export async function seedPages(
  { payload }: SeedContext,
  boards: SeedBoards,
  media: SeedMedia,
  ads: Advertisement[],
): Promise<Page[]> {
  logStep('Seeding pages')

  const home = await upsertByUnique<Page>({
    payload,
    collection: 'pages',
    uniqueField: 'slug',
    uniqueValue: 'home',
    data: {
      title: 'Mod-B Home',
      slug: 'home',
      status: 'published',
      layout: [
        {
          blockType: 'heroSlider',
          title: 'Welcome to Mod-B',
          subtitle: 'A complete demo homepage for latest, popular, trending, gallery, ads, and recent comments.',
          slides: media.hero.map((image, index) => ({
            image: image.id,
            title: `Mod-B Hero Slide ${index + 1}`,
            subtitle: 'Generated by Mod-B seed.',
            buttonLabel: index === 0 ? 'Visit Free Board' : 'Explore Gallery',
            buttonUrl: index === 0 ? '/board/free' : '/board/gallery',
            isActive: true,
            order: index,
          })),
        },
        {
          blockType: 'richTextBlock',
          content: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    { type: 'text', text: 'This home page was generated by the Mod-B seed. Use it to test blocks, board sections, ads, and navigation.', version: 1 },
                  ],
                },
              ],
            },
          },
        },
        { blockType: 'latestPosts', title: 'Latest Mod-B Posts', postCount: 8, boards: boardRefs(boards.free, boards.qna, boards.gallery, boards.market) },
        { blockType: 'popularPosts', title: 'Popular Mod-B Posts', postCount: 6, boards: boardRefs(boards.free, boards.gallery, boards.market) },
        { blockType: 'trendingPosts', title: 'Trending Mod-B Posts', postCount: 6, boards: boardRefs(boards.free, boards.gallery, boards.market) },
        // BoardGrid block intentionally skipped in Mod-B seed v4 because this project's BoardGridBlock
        // validates its `boards` field with a custom shape. Once src/blocks/BoardGrid/config.ts
        // is available, this block can be restored with the exact expected payload.
        { blockType: 'singleBoard', title: 'Free Board Preview', board: boards.free.id, postCount: 6, displayType: 'list' },
        { blockType: 'advertisementBlock', title: 'Sponsored QA', advertisement: ads[0]?.id },
        { blockType: 'recentComments', title: 'Recent Mod-B Comments', commentCount: 8, boards: boardRefs(boards.free, boards.qna, boards.gallery) },
      ] as any,
      meta: {
        title: 'Mod-B Home',
        description: 'Seeded home page for testing Payload CMS board features.',
        image: media.hero[0]?.id,
      },
    },
  })

  const terms = await upsertByUnique<Page>({
    payload,
    collection: 'pages',
    uniqueField: 'slug',
    uniqueValue: 'terms',
    data: {
      title: 'Terms of Service',
      slug: 'terms',
      status: 'published',
      layout: [
        {
          blockType: 'richTextBlock',
          content: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [{ type: 'text', text: 'Mod-B seed terms page content.', version: 1 }],
                },
              ],
            },
          },
        },
      ] as any,
    },
  })

  const privacy = await upsertByUnique<Page>({
    payload,
    collection: 'pages',
    uniqueField: 'slug',
    uniqueValue: 'privacy',
    data: {
      title: 'Privacy Policy',
      slug: 'privacy',
      status: 'published',
      layout: [
        {
          blockType: 'richTextBlock',
          content: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [{ type: 'text', text: 'Mod-B seed privacy page content.', version: 1 }],
                },
              ],
            },
          },
        },
      ] as any,
    },
  })

  return [home, terms, privacy]
}
