/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    boards: Board;
    posts: Post;
    comments: Comment;
    advertisements: Advertisement;
    pages: Page;
    announcements: Announcement;
    'login-logs': LoginLog;
    'audit-logs': AuditLog;
    reports: Report;
    notifications: Notification;
    'bookmark-folders': BookmarkFolder;
    'bookmark-items': BookmarkItem;
    'media-categories': MediaCategory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    boards: BoardsSelect<false> | BoardsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    advertisements: AdvertisementsSelect<false> | AdvertisementsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'login-logs': LoginLogsSelect<false> | LoginLogsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'bookmark-folders': BookmarkFoldersSelect<false> | BookmarkFoldersSelect<true>;
    'bookmark-items': BookmarkItemsSelect<false> | BookmarkItemsSelect<true>;
    'media-categories': MediaCategoriesSelect<false> | MediaCategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'date-time-settings': DateTimeSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'date-time-settings': DateTimeSettingsSelect<false> | DateTimeSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  nickname: string;
  role: 'admin' | 'manager' | 'member';
  /**
   * User level for gamification
   */
  level?: number | null;
  /**
   * Inactive accounts cannot log in
   */
  isActive?: boolean | null;
  avatar?: (number | null) | Media;
  socialAvatarUrl?: string | null;
  bio?: string | null;
  emailVerified?: boolean | null;
  emailVerificationToken?: string | null;
  emailVerificationExpires?: string | null;
  /**
   * Social login provider used to create this account
   */
  socialProvider?: ('google' | 'naver' | 'kakao' | 'facebook') | null;
  socialProviderAccountId?: string | null;
  termsAccepted?: boolean | null;
  profileCompleted?: boolean | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  category?: (number | null) | MediaCategory;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-categories".
 */
export interface MediaCategory {
  id: number;
  name: string;
  /**
   * Examples: post-image, attachment, hero
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boards".
 */
export interface Board {
  id: number;
  name: string;
  /**
   * Example: free-board, gallery, notice (Spaces are allowed but not recommended. Please use hyphens instead.)
   */
  slug: string;
  description?: string | null;
  boardType: 'list' | 'card' | 'gallery' | 'compact' | 'notice' | 'qna';
  listSettings?: {
    postsPerPage?: number | null;
    showAuthor?: boolean | null;
    showDate?: boolean | null;
    showViewCount?: boolean | null;
  };
  announcementSettings?: {
    enablePinnedNotices?: boolean | null;
    maxPinnedNotices?: number | null;
  };
  writeSettings?: {
    allowWrite?: ('member' | 'manager' | 'admin') | null;
    /**
     * Who can write comments. This only applies when Allow Comment is enabled.
     */
    allowCommentWrite?: ('member' | 'manager' | 'admin') | null;
    allowComment?: boolean | null;
    allowAnonymous?: boolean | null;
    allowAnonymousComment?: boolean | null;
    allowAttachment?: boolean | null;
    maxAttachments?: number | null;
  };
  skinSettings?: {
    gridColumns?: ('1' | '2' | '3' | '4') | null;
  };
  /**
   * Smaller numbers are displayed first
   */
  order?: number | null;
  isActive?: boolean | null;
  /**
   * Users who can manage this board.
   */
  managers?: (number | User)[] | null;
  /**
   * Disable this to temporarily prevent managers from managing this board.
   */
  managerEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  board: number | Board;
  author?: (number | null) | User;
  /**
   * Admin only: use HTML content instead of rich text
   */
  useHtmlContent?: boolean | null;
  /**
   * Admin only: direct HTML input
   */
  contentHtml?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  attachments?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  viewCount?: number | null;
  likeCount?: number | null;
  isNotice?: boolean | null;
  isSecret?: boolean | null;
  /**
   * Mark this Q&A post as answered
   */
  isAnswered?: boolean | null;
  /**
   * ID of the accepted answer comment
   */
  acceptedCommentId?: number | null;
  status?: ('published' | 'draft' | 'deleted') | null;
  /**
   * Display name for anonymous posts
   */
  anonymousAuthor?: string | null;
  /**
   * Stored for moderation only. Do not display publicly.
   */
  anonymousIp?: string | null;
  anonymousPasswordHash?: string | null;
  /**
   * Stored for moderation only.
   */
  anonymousUserAgent?: string | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  restoredAt?: string | null;
  restoredBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  author?: (number | null) | User;
  anonymousAuthor?: string | null;
  anonymousIp?: string | null;
  anonymousPasswordHash?: string | null;
  anonymousUserAgent?: string | null;
  content: string;
  /**
   * Select parent comment for replies
   */
  parentComment?: (number | null) | Comment;
  likeCount?: number | null;
  /**
   * Show "Deleted comment" message when checked
   */
  isDeleted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advertisements".
 */
export interface Advertisement {
  id: number;
  title: string;
  adType: 'slide' | 'grid' | 'banner' | 'adsense';
  image?: (number | null) | Media;
  linkUrl?: string | null;
  linkTarget?: ('_blank' | '_self') | null;
  altText?: string | null;
  /**
   * Specifies the horizontal width of the advertisement image
   */
  widthType?: ('full' | 'content' | 'custom') | null;
  /**
   * 예: 728px, 100%, 50vw
   */
  customWidth?: string | null;
  /**
   * 예: 90px, 250px, auto (비워두면 자동)
   */
  customHeight?: string | null;
  objectFit?: ('cover' | 'contain' | 'fill') | null;
  /**
   * Groups slides together into a single slider (e.g., hero-slider)
   */
  slideGroup?: string | null;
  slideOrder?: number | null;
  /**
   * Groups grid items together into a single grid (e.g., sidebar-grid)
   */
  gridGroup?: string | null;
  gridColumns?: ('2' | '3' | '4') | null;
  gridOrder?: number | null;
  /**
   * Paste the <ins> tag code issued from Google Adsense
   */
  adsenseCode?: string | null;
  positions: ('board-top' | 'board-middle' | 'board-bottom' | 'post-top' | 'post-bottom' | 'sidebar' | 'home')[];
  /**
   * 5 → 5th post after
   */
  middlePosition?: number | null;
  /**
   * Leave empty to display on all boards
   */
  targetBoards?: (number | Board)[] | null;
  startDate?: string | null;
  endDate?: string | null;
  isActive?: boolean | null;
  /**
   * The lower the number, the higher the priority
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage. e.g. home, about, event
   */
  slug: string;
  layout?:
    | (
        | {
            slides?:
              | {
                  image: number | Media;
                  title?: string | null;
                  subtitle?: string | null;
                  linkUrl?: string | null;
                  linkLabel?: string | null;
                  linkTarget?: ('_self' | '_blank') | null;
                  id?: string | null;
                }[]
              | null;
            heightType?: ('small' | 'medium' | 'large' | 'full' | 'custom') | null;
            /**
             * e.g. 400px, 60vh
             */
            customHeight?: string | null;
            autoPlay?: boolean | null;
            autoPlayInterval?: number | null;
            showDots?: boolean | null;
            showArrows?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSlider';
          }
        | {
            sectionTitle?: string | null;
            boards?:
              | {
                  board: number | Board;
                  customTitle?: string | null;
                  postCount?: number | null;
                  displayType?: ('list' | 'card' | 'gallery' | 'compact') | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('1' | '2' | '3' | '4') | null;
            showMoreLink?: boolean | null;
            showAuthor?: boolean | null;
            showDate?: boolean | null;
            showViewCount?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'boardGrid';
          }
        | {
            sectionTitle?: string | null;
            postCount?: number | null;
            filterBoards?: (number | Board)[] | null;
            displayType?: ('list' | 'card' | 'gallery' | 'compact') | null;
            gridColumns?: ('1' | '2' | '3' | '4') | null;
            showBoardName?: boolean | null;
            showAuthor?: boolean | null;
            showDate?: boolean | null;
            showViewCount?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestPosts';
          }
        | {
            sectionTitle?: string | null;
            postCount?: number | null;
            /**
             * Collect trending posts from the last N days based on view count.
             */
            periodDays?: number | null;
            filterBoards?: (number | Board)[] | null;
            displayType?: ('list' | 'card' | 'gallery' | 'compact') | null;
            gridColumns?: ('1' | '2' | '3' | '4') | null;
            showRanking?: boolean | null;
            showBoardName?: boolean | null;
            showAuthor?: boolean | null;
            showDate?: boolean | null;
            showViewCount?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trendingPosts';
          }
        | {
            sectionTitle?: string | null;
            postCount?: number | null;
            filterBoards?: (number | Board)[] | null;
            displayType?: ('list' | 'card' | 'gallery' | 'compact') | null;
            gridColumns?: ('1' | '2' | '3' | '4') | null;
            showRanking?: boolean | null;
            showBoardName?: boolean | null;
            showAuthor?: boolean | null;
            showDate?: boolean | null;
            showViewCount?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'popularPosts';
          }
        | {
            board: number | Board;
            customTitle?: string | null;
            postCount?: number | null;
            displayType?: ('list' | 'card' | 'gallery' | 'compact') | null;
            gridColumns?: ('1' | '2' | '3' | '4') | null;
            showAuthor?: boolean | null;
            showDate?: boolean | null;
            showViewCount?: boolean | null;
            showMoreLink?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singleBoard';
          }
        | {
            adType: 'single' | 'slide' | 'grid' | 'adsense';
            /**
             * Renders all active ads with matching slide group name
             */
            slideGroup?: string | null;
            /**
             * Renders all active ads with matching grid group name
             */
            gridGroup?: string | null;
            gridColumns?: ('2' | '3' | '4') | null;
            singleAd?: (number | null) | Advertisement;
            /**
             * e.g. 1234567890
             */
            adsenseSlot?: string | null;
            widthType?: ('full' | 'content') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advertisementBlock';
          }
        | {
            /**
             * Admin only. Use raw HTML instead of the rich text editor.
             */
            useHtmlContent?: boolean | null;
            /**
             * Admin only: direct HTML input
             */
            contentHtml?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            widthType?: ('full' | 'content' | 'narrow') | null;
            alignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            image: number | Media;
            altText?: string | null;
            linkUrl?: string | null;
            linkTarget?: ('_self' | '_blank') | null;
            widthType?: ('full' | 'content' | 'custom') | null;
            /**
             * e.g. 728px, 50%
             */
            customWidth?: string | null;
            /**
             * e.g. 90px, auto
             */
            customHeight?: string | null;
            objectFit?: ('cover' | 'contain' | 'fill') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerBlock';
          }
        | {
            sectionTitle?: string | null;
            commentCount?: number | null;
            filterBoards?: (number | Board)[] | null;
            showBoardName?: boolean | null;
            showAuthor?: boolean | null;
            showDate?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recentComments';
          }
      )[]
    | null;
  status?: ('published' | 'draft') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  message?: string | null;
  linkType?: ('none' | 'custom' | 'page' | 'board') | null;
  customUrl?: string | null;
  pageLink?: (number | null) | Page;
  boardLink?: (number | null) | Board;
  displayType?: ('ticker' | 'bar') | null;
  startDate?: string | null;
  endDate?: string | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs".
 */
export interface LoginLog {
  id: number;
  eventType: 'login' | 'logout';
  user: number | User;
  email: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  loginMethod?: ('password' | 'google' | 'naver' | 'kakao' | 'facebook') | null;
  success?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete' | 'restore' | 'verify' | 'report' | 'moderate';
  resourceType: 'post' | 'comment' | 'user' | 'board' | 'report';
  resourceId: string;
  actorType: 'user' | 'anonymous' | 'system';
  actor?: (number | null) | User;
  anonymousAuthor?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  message?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  targetType: 'post' | 'comment';
  targetId: string;
  reason: 'spam' | 'abuse' | 'inappropriate' | 'personal_info' | 'other';
  details?: string | null;
  status?: ('open' | 'reviewing' | 'resolved' | 'dismissed') | null;
  reporter?: (number | null) | User;
  reporterIp?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  type: 'comment' | 'reply' | 'qna_answer' | 'qna_accepted' | 'moderation' | 'mention';
  title: string;
  message?: string | null;
  href?: string | null;
  isRead?: boolean | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmark-folders".
 */
export interface BookmarkFolder {
  id: number;
  user: number | User;
  name: string;
  description?: string | null;
  isDefault?: boolean | null;
  isPublic?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmark-items".
 */
export interface BookmarkItem {
  id: number;
  folder: number | BookmarkFolder;
  post: number | Post;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'boards';
        value: number | Board;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'advertisements';
        value: number | Advertisement;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'login-logs';
        value: number | LoginLog;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'bookmark-folders';
        value: number | BookmarkFolder;
      } | null)
    | ({
        relationTo: 'bookmark-items';
        value: number | BookmarkItem;
      } | null)
    | ({
        relationTo: 'media-categories';
        value: number | MediaCategory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  nickname?: T;
  role?: T;
  level?: T;
  isActive?: T;
  avatar?: T;
  socialAvatarUrl?: T;
  bio?: T;
  emailVerified?: T;
  emailVerificationToken?: T;
  emailVerificationExpires?: T;
  socialProvider?: T;
  socialProviderAccountId?: T;
  termsAccepted?: T;
  profileCompleted?: T;
  isDeleted?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boards_select".
 */
export interface BoardsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  boardType?: T;
  listSettings?:
    | T
    | {
        postsPerPage?: T;
        showAuthor?: T;
        showDate?: T;
        showViewCount?: T;
      };
  announcementSettings?:
    | T
    | {
        enablePinnedNotices?: T;
        maxPinnedNotices?: T;
      };
  writeSettings?:
    | T
    | {
        allowWrite?: T;
        allowCommentWrite?: T;
        allowComment?: T;
        allowAnonymous?: T;
        allowAnonymousComment?: T;
        allowAttachment?: T;
        maxAttachments?: T;
      };
  skinSettings?:
    | T
    | {
        gridColumns?: T;
      };
  order?: T;
  isActive?: T;
  managers?: T;
  managerEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  board?: T;
  author?: T;
  useHtmlContent?: T;
  contentHtml?: T;
  content?: T;
  thumbnail?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  viewCount?: T;
  likeCount?: T;
  isNotice?: T;
  isSecret?: T;
  isAnswered?: T;
  acceptedCommentId?: T;
  status?: T;
  anonymousAuthor?: T;
  anonymousIp?: T;
  anonymousPasswordHash?: T;
  anonymousUserAgent?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  restoredAt?: T;
  restoredBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  author?: T;
  anonymousAuthor?: T;
  anonymousIp?: T;
  anonymousPasswordHash?: T;
  anonymousUserAgent?: T;
  content?: T;
  parentComment?: T;
  likeCount?: T;
  isDeleted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advertisements_select".
 */
export interface AdvertisementsSelect<T extends boolean = true> {
  title?: T;
  adType?: T;
  image?: T;
  linkUrl?: T;
  linkTarget?: T;
  altText?: T;
  widthType?: T;
  customWidth?: T;
  customHeight?: T;
  objectFit?: T;
  slideGroup?: T;
  slideOrder?: T;
  gridGroup?: T;
  gridColumns?: T;
  gridOrder?: T;
  adsenseCode?: T;
  positions?: T;
  middlePosition?: T;
  targetBoards?: T;
  startDate?: T;
  endDate?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroSlider?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    linkUrl?: T;
                    linkLabel?: T;
                    linkTarget?: T;
                    id?: T;
                  };
              heightType?: T;
              customHeight?: T;
              autoPlay?: T;
              autoPlayInterval?: T;
              showDots?: T;
              showArrows?: T;
              id?: T;
              blockName?: T;
            };
        boardGrid?:
          | T
          | {
              sectionTitle?: T;
              boards?:
                | T
                | {
                    board?: T;
                    customTitle?: T;
                    postCount?: T;
                    displayType?: T;
                    id?: T;
                  };
              columns?: T;
              showMoreLink?: T;
              showAuthor?: T;
              showDate?: T;
              showViewCount?: T;
              id?: T;
              blockName?: T;
            };
        latestPosts?:
          | T
          | {
              sectionTitle?: T;
              postCount?: T;
              filterBoards?: T;
              displayType?: T;
              gridColumns?: T;
              showBoardName?: T;
              showAuthor?: T;
              showDate?: T;
              showViewCount?: T;
              id?: T;
              blockName?: T;
            };
        trendingPosts?:
          | T
          | {
              sectionTitle?: T;
              postCount?: T;
              periodDays?: T;
              filterBoards?: T;
              displayType?: T;
              gridColumns?: T;
              showRanking?: T;
              showBoardName?: T;
              showAuthor?: T;
              showDate?: T;
              showViewCount?: T;
              id?: T;
              blockName?: T;
            };
        popularPosts?:
          | T
          | {
              sectionTitle?: T;
              postCount?: T;
              filterBoards?: T;
              displayType?: T;
              gridColumns?: T;
              showRanking?: T;
              showBoardName?: T;
              showAuthor?: T;
              showDate?: T;
              showViewCount?: T;
              id?: T;
              blockName?: T;
            };
        singleBoard?:
          | T
          | {
              board?: T;
              customTitle?: T;
              postCount?: T;
              displayType?: T;
              gridColumns?: T;
              showAuthor?: T;
              showDate?: T;
              showViewCount?: T;
              showMoreLink?: T;
              id?: T;
              blockName?: T;
            };
        advertisementBlock?:
          | T
          | {
              adType?: T;
              slideGroup?: T;
              gridGroup?: T;
              gridColumns?: T;
              singleAd?: T;
              adsenseSlot?: T;
              widthType?: T;
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              useHtmlContent?: T;
              contentHtml?: T;
              content?: T;
              widthType?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        bannerBlock?:
          | T
          | {
              image?: T;
              altText?: T;
              linkUrl?: T;
              linkTarget?: T;
              widthType?: T;
              customWidth?: T;
              customHeight?: T;
              objectFit?: T;
              id?: T;
              blockName?: T;
            };
        recentComments?:
          | T
          | {
              sectionTitle?: T;
              commentCount?: T;
              filterBoards?: T;
              showBoardName?: T;
              showAuthor?: T;
              showDate?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  linkType?: T;
  customUrl?: T;
  pageLink?: T;
  boardLink?: T;
  displayType?: T;
  startDate?: T;
  endDate?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-logs_select".
 */
export interface LoginLogsSelect<T extends boolean = true> {
  eventType?: T;
  user?: T;
  email?: T;
  ipAddress?: T;
  userAgent?: T;
  loginMethod?: T;
  success?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  resourceType?: T;
  resourceId?: T;
  actorType?: T;
  actor?: T;
  anonymousAuthor?: T;
  ip?: T;
  userAgent?: T;
  message?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  targetType?: T;
  targetId?: T;
  reason?: T;
  details?: T;
  status?: T;
  reporter?: T;
  reporterIp?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  href?: T;
  isRead?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmark-folders_select".
 */
export interface BookmarkFoldersSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  description?: T;
  isDefault?: T;
  isPublic?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmark-items_select".
 */
export interface BookmarkItemsSelect<T extends boolean = true> {
  folder?: T;
  post?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-categories_select".
 */
export interface MediaCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  siteLogo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  homeSettings?: {
    heroSettings?: {
      enabled?: boolean | null;
      sliderSettings?: {
        autoPlay?: boolean | null;
        autoPlayInterval?: number | null;
        showDots?: boolean | null;
        showArrows?: boolean | null;
        width?: ('content' | 'full') | null;
        heightType?: ('small' | 'medium' | 'large' | 'full' | 'custom') | null;
        /**
         * ex: 420px, 60vh
         */
        customHeight?: string | null;
      };
      slides?:
        | {
            image: number | Media;
            title?: string | null;
            subtitle?: string | null;
            linkUrl?: string | null;
            linkLabel?: string | null;
            linkTarget?: ('_self' | '_blank') | null;
            order?: number | null;
            isActive?: boolean | null;
            id?: string | null;
          }[]
        | null;
    };
    globalBoardSettings?: {
      /**
       * Show global board sections in the site sidebar.
       */
      enabled?: boolean | null;
      visibility?: {
        showOnHome?: boolean | null;
        showOnBoard?: boolean | null;
        showOnPost?: boolean | null;
        showOnSearch?: boolean | null;
        showOnTag?: boolean | null;
        showOnUser?: boolean | null;
        showOnMyPage?: boolean | null;
        showOnLogin?: boolean | null;
      };
      /**
       * Show sidebar advertisements below the global board sections.
       */
      enableSidebarAds?: boolean | null;
      position?: ('left' | 'right') | null;
      /**
       * Global board sections and post counts
       */
      boardSections?:
        | {
            sectionType?:
              | ('board' | 'latest' | 'trending' | 'popular' | 'recentComments' | 'page' | 'custom' | 'advertisement')
              | null;
            advertisement?: (number | null) | Advertisement;
            /**
             * Select boards to include in Latest Posts. Leave empty to include all boards.
             */
            boards?: (number | Board)[] | null;
            board?: (number | null) | Board;
            /**
             * If empty, board name will be used.
             */
            sectionTitle?: string | null;
            postCount?: number | null;
            displayType?: ('ticker' | 'list' | 'card' | 'gallery') | null;
            /**
             * Used for Card, Gallery, and Compact display types.
             */
            gridColumns?: ('1' | '2' | '3' | '4') | null;
            order?: number | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * SMTP settings are configured via .env file. Shown here for reference only.
   */
  email?: {
    smtpHost?: string | null;
    smtpPort?: string | null;
    smtpUser?: string | null;
    fromName?: string | null;
    fromEmail?: string | null;
    requireEmailVerification?: boolean | null;
  };
  socialLogin?: {
    google?: {
      enabled?: boolean | null;
      buttonLabel?: string | null;
    };
    naver?: {
      enabled?: boolean | null;
      buttonLabel?: string | null;
    };
    kakao?: {
      enabled?: boolean | null;
      buttonLabel?: string | null;
    };
    facebook?: {
      enabled?: boolean | null;
      buttonLabel?: string | null;
    };
    dividerText?: string | null;
  };
  /**
   * Customize colors, fonts, and layout for your site.
   */
  design?: {
    colors?: {
      /**
       * Main brand color (hex). e.g. #111827
       */
      primary?: string | null;
      /**
       * Text color on primary background
       */
      primaryForeground?: string | null;
      /**
       * Secondary/accent color
       */
      secondary?: string | null;
      /**
       * Text color on secondary background
       */
      secondaryForeground?: string | null;
      /**
       * Background color for the entire page
       */
      background?: string | null;
      /**
       * Text color for the entire page
       */
      foreground?: string | null;
      headerBg?: string | null;
      navBg?: string | null;
      footerBg?: string | null;
      footerFg?: string | null;
      link?: string | null;
    };
    typography?: {
      fontFamily?: ('system' | 'inter' | 'noto-sans-kr' | 'pretendard' | 'roboto' | 'open-sans' | 'custom') | null;
      baseFontSize?: ('14px' | '15px' | '16px' | '17px' | '18px') | null;
      headingWeight?: ('400' | '500' | '600' | '700' | '800') | null;
    };
    layout?: {
      maxWidth?: ('1024px' | '1280px' | '1440px' | '100%') | null;
      borderRadius?: ('0px' | '4px' | '8px' | '12px' | '16px') | null;
      headerHeight?: ('56px' | '64px' | '72px' | '80px') | null;
      headerWidth?: ('content' | 'full') | null;
      navWidth?: ('content' | 'full') | null;
      announcementWidth?: ('content' | 'full') | null;
      mainWidth?: ('content' | 'full') | null;
      footerWidth?: ('content' | 'full') | null;
    };
    /**
     * Add custom CSS rules. Applied globally to all pages.
     */
    customCss?: string | null;
  };
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * 예: G-XXXXXXXXXX
     */
    googleAnalyticsId?: string | null;
    naverVerification?: string | null;
    googleVerification?: string | null;
  };
  googleAds?: {
    enabled?: boolean | null;
    /**
     * e.g., ca-pub-XXXXXXXXXXXXXXXX
     */
    publisherId?: string | null;
    /**
     * Google will automatically determine ad placements
     */
    autoAds?: boolean | null;
  };
  customScripts?: {
    /**
     * All pages <head> will have this script inserted
     */
    headScript?: string | null;
    /**
     * All pages </body> will have this script inserted
     */
    bodyScript?: string | null;
  };
  forbiddenWords?: {
    /**
     * Forbidden words for name and nickname (ex: admin, manager, operator)
     */
    registration?: string | null;
    /**
     * Forbidden words for posts and comments (ex: spam, scam, fake)
     */
    content?: string | null;
  };
  /**
   * If enabled, access for all regular visitors will be blocked except for administrators.
   */
  maintenance?: {
    enabled?: boolean | null;
    title?: string | null;
    message?: string | null;
    estimatedDate?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Add and reorder menu items. Drag to reorder.
   */
  items?:
    | {
        label: string;
        type: 'board' | 'dropdown' | 'url' | 'page';
        board?: (number | null) | Board;
        /**
         * e.g. /about or https://example.com
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        page?: (number | null) | Page;
        /**
         * Optional link for the dropdown title itself.
         */
        dropdownLinkType?: ('none' | 'page' | 'url') | null;
        dropdownPage?: (number | null) | Page;
        /**
         * e.g. /it or https://example.com
         */
        dropdownUrl?: string | null;
        dropdownOpenInNewTab?: boolean | null;
        /**
         * Sub-menu items shown in dropdown
         */
        children?:
          | {
              label: string;
              type?: ('board' | 'url' | 'page') | null;
              board?: (number | null) | Board;
              url?: string | null;
              openInNewTab?: boolean | null;
              page?: (number | null) | Page;
              id?: string | null;
            }[]
          | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    columns?: ('2' | '3' | '4') | null;
    /**
     * Add columns to the footer. Number of columns is set above.
     */
    columnItems?:
      | {
          title?: string | null;
          links?:
            | {
                label: string;
                type?: ('page' | 'board' | 'url') | null;
                page?: (number | null) | Page;
                board?: (number | null) | Board;
                /**
                 * e.g. /about or https://example.com
                 */
                url?: string | null;
                openInNewTab?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    bottomBar?: {
      copyrightName?: string | null;
      showYear?: boolean | null;
      bottomLinks?:
        | {
            label: string;
            type?: ('page' | 'board' | 'url' | 'email') | null;
            page?: (number | null) | Page;
            board?: (number | null) | Board;
            url?: string | null;
            email?: string | null;
            openInNewTab?: boolean | null;
            id?: string | null;
          }[]
        | null;
      rightText?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "date-time-settings".
 */
export interface DateTimeSetting {
  id: number;
  enabled?: boolean | null;
  displayMode?: ('rolling' | 'inline') | null;
  showWeather?: boolean | null;
  showDateTime?: boolean | null;
  locations?:
    | {
        label: string;
        icon?: string | null;
        /**
         * Example: Pacific/Honolulu, Asia/Seoul, America/New_York
         */
        timeZone: string;
        latitude: number;
        longitude: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  siteLogo?: T;
  favicon?: T;
  homeSettings?:
    | T
    | {
        heroSettings?:
          | T
          | {
              enabled?: T;
              sliderSettings?:
                | T
                | {
                    autoPlay?: T;
                    autoPlayInterval?: T;
                    showDots?: T;
                    showArrows?: T;
                    width?: T;
                    heightType?: T;
                    customHeight?: T;
                  };
              slides?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    linkUrl?: T;
                    linkLabel?: T;
                    linkTarget?: T;
                    order?: T;
                    isActive?: T;
                    id?: T;
                  };
            };
        globalBoardSettings?:
          | T
          | {
              enabled?: T;
              visibility?:
                | T
                | {
                    showOnHome?: T;
                    showOnBoard?: T;
                    showOnPost?: T;
                    showOnSearch?: T;
                    showOnTag?: T;
                    showOnUser?: T;
                    showOnMyPage?: T;
                    showOnLogin?: T;
                  };
              enableSidebarAds?: T;
              position?: T;
              boardSections?:
                | T
                | {
                    sectionType?: T;
                    advertisement?: T;
                    boards?: T;
                    board?: T;
                    sectionTitle?: T;
                    postCount?: T;
                    displayType?: T;
                    gridColumns?: T;
                    order?: T;
                    id?: T;
                  };
            };
      };
  email?:
    | T
    | {
        smtpHost?: T;
        smtpPort?: T;
        smtpUser?: T;
        fromName?: T;
        fromEmail?: T;
        requireEmailVerification?: T;
      };
  socialLogin?:
    | T
    | {
        google?:
          | T
          | {
              enabled?: T;
              buttonLabel?: T;
            };
        naver?:
          | T
          | {
              enabled?: T;
              buttonLabel?: T;
            };
        kakao?:
          | T
          | {
              enabled?: T;
              buttonLabel?: T;
            };
        facebook?:
          | T
          | {
              enabled?: T;
              buttonLabel?: T;
            };
        dividerText?: T;
      };
  design?:
    | T
    | {
        colors?:
          | T
          | {
              primary?: T;
              primaryForeground?: T;
              secondary?: T;
              secondaryForeground?: T;
              background?: T;
              foreground?: T;
              headerBg?: T;
              navBg?: T;
              footerBg?: T;
              footerFg?: T;
              link?: T;
            };
        typography?:
          | T
          | {
              fontFamily?: T;
              baseFontSize?: T;
              headingWeight?: T;
            };
        layout?:
          | T
          | {
              maxWidth?: T;
              borderRadius?: T;
              headerHeight?: T;
              headerWidth?: T;
              navWidth?: T;
              announcementWidth?: T;
              mainWidth?: T;
              footerWidth?: T;
            };
        customCss?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        ogImage?: T;
        googleAnalyticsId?: T;
        naverVerification?: T;
        googleVerification?: T;
      };
  googleAds?:
    | T
    | {
        enabled?: T;
        publisherId?: T;
        autoAds?: T;
      };
  customScripts?:
    | T
    | {
        headScript?: T;
        bodyScript?: T;
      };
  forbiddenWords?:
    | T
    | {
        registration?: T;
        content?: T;
      };
  maintenance?:
    | T
    | {
        enabled?: T;
        title?: T;
        message?: T;
        estimatedDate?: T;
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        type?: T;
        board?: T;
        url?: T;
        openInNewTab?: T;
        page?: T;
        dropdownLinkType?: T;
        dropdownPage?: T;
        dropdownUrl?: T;
        dropdownOpenInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              board?: T;
              url?: T;
              openInNewTab?: T;
              page?: T;
              id?: T;
            };
        isActive?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        columns?: T;
        columnItems?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    board?: T;
                    url?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
            };
        bottomBar?:
          | T
          | {
              copyrightName?: T;
              showYear?: T;
              bottomLinks?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    board?: T;
                    url?: T;
                    email?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              rightText?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "date-time-settings_select".
 */
export interface DateTimeSettingsSelect<T extends boolean = true> {
  enabled?: T;
  displayMode?: T;
  showWeather?: T;
  showDateTime?: T;
  locations?:
    | T
    | {
        label?: T;
        icon?: T;
        timeZone?: T;
        latitude?: T;
        longitude?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}